# Generated by Django 4.2.1 on 2023-06-04 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_note_content_alter_note_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Console',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('released', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='game',
            name='console',
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.CharField(max_length=500, verbose_name='content of note'),
        ),
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='posted on'),
        ),
        migrations.AlterField(
            model_name='note',
            name='type',
            field=models.CharField(choices=[('T', 'Thoughts'), ('R', 'Review'), ('P', 'Progress')], default='T', max_length=1, verbose_name='type of note'),
        ),
        migrations.AddField(
            model_name='game',
            name='console',
            field=models.ManyToManyField(to='main_app.console'),
        ),
    ]
