# Generated by Django 4.2.1 on 2023-06-04 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_console_alter_note_options_remove_game_console_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Console',
            new_name='Consoles',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='console',
            new_name='consoles',
        ),
    ]
