# Generated by Django 4.2.1 on 2023-06-04 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_rename_consoles_console_remove_game_consoles'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='consoles',
            field=models.ManyToManyField(to='main_app.console'),
        ),
    ]
